variables:
  IMAGE_NAME: prajwalsontakke98/firstcustomimage
  IMAGE_TAG: contact-app

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
  script:
      - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@13.53.134.232 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker run -d -p 5173:5173 $IMAGE_NAME:$IMAGE_TAG"
